# Generated by Django 3.0.1 on 2020-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
        migrations.AddField(
            model_name='vote',
            name='liked',
            field=models.IntegerField(null=True),
        ),
    ]
