# Generated by Django 3.0.1 on 2020-01-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_auto_20200125_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='liked',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
