# Generated by Django 3.0.1 on 2020-01-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_auto_20200125_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
